### ISSUE TITLE
Spare Linear Matrix Solver

### ISSUE THREAD

**Issue by kesleta** [sparsemat/sprs#322]
Sorry if I'm overlooking something obvious here, but does this library include a way to solve sparse matrix equations? E.g. I have a matrix `A` and a vector `v` and I want to find the vector x`` that satisfies the equation `Ax=v`. I looked in the documentation and could not find any functions under "inverse" or "solve" other than the triangular solvers, which seem like they are meant only for a specialized case. Is there, or is there planned to be, a method of solving such equations using this library? Thank you for any help or guidance.

**Comment by mulimoen** [comment]
There is the `sprs_ldl` package for solving a hermitian positive definite matrix. Have a look at suitesparse and we could see if a wrapper for some function might fit your usecase

**Comment by jlogan03** [comment]
I have a pr out (https://github.com/sparsemat/sprs/pull/327) to add bindings to umfpack, which handles more general square systems - hopefully that helps

**Comment by jlogan03** [comment]
@kesleta ,  #327 is merged, so you should be able to use the methods in sprs_suitesparse_umfpack to do arbitrary square Ax=b solves with a dense right-hand-side.
