### ISSUE TITLE
Modifying the default implementation for `MulAcc`. 

### ISSUE THREAD

**Issue by taketo1024** [sparsemat/sprs#323]
I'd like to use `sprs` with [`num-bigint`](https://github.com/rust-num/num-bigint), [`num-rational`](https://github.com/rust-num/num-rational) etc. However, `sprs`'s matrix multiplication requires that the scalar type implements `MulAcc`, which `BigInt` and `Rational` types do not suffice. 

We can make these types automatically implement `MulAcc`, if we change the code in [`mul_acc.rs`](https://github.com/sparsemat/sprs/blob/master/sprs/src/mul_acc.rs) from the current

```rust
impl<N, A, B> MulAcc<A, B> for N
where
    N: Copy,
    B: Copy,
    A: num_traits::MulAdd<B, N, Output = N> + Copy,
{
    fn mul_acc(&mut self, a: &A, b: &B) {
        *self = a.mul_add(*b, *self);
    }
}
```

to

```rust
impl<N, A, B> MulAcc<A, B> for N
where
    for<'x> &'x A: Mul<&'x B, Output = N>,
    N: AddAssign<N> 
{
    fn mul_acc(&mut self, a: &A, b: &B) {
        self.add_assign(a * b);
    }
}
```

Is this a bad idea?  (regarding performance?)
Thanks.

**Comment by taketo1024** [comment]
I have pushed the modified version on my folked repo. https://github.com/taketo1024/sprs/tree/mul_acc_default. 
I will send a PR if this modification seems good.

**Comment by mulimoen** [comment]
That seems like a good idea. We can judge the performance impact once the PR is up

**Comment by taketo1024** [comment]
Created PR. Closing this issue. Thanks!
